In [32]:
import base64
import json
from google.oauth2 import service_account

# Paste your Base64 string directly (no environment variable needed)
TEST_BASE64 = "ewogICJ0eXBlIjogInNlcnZpY2VfYWNjb3VudCIsCiAgInByb2plY3RfaWQiOiAicGVyZmVjdC1kYXktNDM3ODAyLXE1IiwKICAicHJpdmF0ZV9rZXlfaWQiOiAiOWYwM2I4Y2RhYTk5ZGFhMDkzMjFlZjQwYjg0NDU4NTdjOTY0MjRjYSIsCiAgInByaXZhdGVfa2V5IjogIi0tLS0tQkVHSU4gUFJJVkFURSBLRVktLS0tLVxuTUlJRXZBSUJBREFOQmdrcWhraUc5dzBCQVFFRkFBU0NCS1l3Z2dTaUFnRUFBb0lCQVFETjBFSE85Q3QwczJ3bVxuOWRRZldIaXliUDd6Z0k4dTZHQk5DZ2c2NzdYZ25TY0ZoUDkvNmRhb1dkcGxvYTd1NmNoN2x1ZHUzMHRUcVMycVxuU0tONkZtc0dZTFJtNUorR2NiRDN3R01Vbk5raU5UdHpaS3FEcVpkbjl3Qno3VXVQVDhRbFhsQjdWaWxROElscVxuN2JxSHF3aTdHaUJPRDBzZC9SMWhkNGthK0hZSlQ1WWx2V3pEQ3VDQ3I2SGxNNVFPS0QrcitUYTE5Sk1qMnNUL1xuTFhtTVJqY3pDbWJnY00wU0JSWHpIa3NmOFRGN1VzVk55TXFua3F3VFFNOVZlck5mNUcyaHVEbWlrQVRkQXFoeFxuN2VESG44VS9ZdEo5c0I5WE5GL3p0L1hadW9rTjh6RDIxSUZUWHJQV3YxVi9iam1BaSsrbldOM2lNTStCdVZaTFxuNlRqam9INzlBZ01CQUFFQ2dnRUFKRklMd3dkeEFjdkdHc3dJTHEzd3d1QWNVQUdRZ3lFc0dYeGJQbmRlRy9EdlxuMlhnQ2xPTEI2SHpPMzErY25QbngwT210RnZKZCt6b2dYbXdxT1ZucWNqb3ZxL2JOdGk2cklkVzRSb04xaUNWblxudy9Id2E0TEt2dVNtbGs2NnBtUlh3NVowMG9jK2pGT2VsSm0yY01tOHBUUXpua0x4cVMycGVURmNwejlRcVV5cVxub2hxeWF2NFNHWTFqY3Vzd2lRd3B5V3NwZUR6N0xaZjJyK2xoajRBQW8xeU90dDFyZm9GNml3ZFd6QU52ME8vdlxuSEJiU00yUCtnMDhic0tzYWxBRTd0L3BhSzhyUENDcUxQcjVKcTM5TFBwRk9JQ0dXZmNvUjJjM1d2dXp6VHJJNFxucll2T3RNTU1haHJadWFNc3VMZlZRWHVkdE1vcVBQbldYVUt4ZzJSUFVRS0JnUUR3bHFGYlpPY2E3elFYSXVLa1xucHJIR2R6NE1waGVHejRMcGFOazM0YzJlM2lWUVBqK0N5bmx2Qy9HdDVGek1DSVdoY05WYllRTTBNd2d6WXNIcVxuR0w5VWtuQ3lnQUt0TzR4SlFCY3JsYmxIRVhWaWYrRlJkMGY5M3dRalpveXBjZUpTUkhjTjZuMGdHMU9HMUZoYVxuY1Vsb29HbXZnQlBhSVNDVnlhbDJhdXRmNVFLQmdRRGEvMXZrbmpoZ2tvSklORGdBVjlUTEl0anFlMkpqMlVydlxubHJuZDdkdnNBUkRwNDhrNS9XcXJoMjdORkpLdlFueVJnZDRsU1E2dDJFaDYxdVJSNXcwRmR6a01aUElsNTh0RlxubHVUMjZ2czBxV2ZGc0EzOE9rbU9jKzdtRTkrY1dZelpoYmd2MUtPSGdxTzJaZFB2Vk1BNGNRcFFjMmM3TC9jQlxuWitWMFpuTkJPUUtCZ0I3WjhnOGFQVmlDM0JjcmJnelhJMnpqMVowaG4xcTJPWDljNXAzMzRycEFtbUJUMnlrV1xuZGNQN3NCNHdib1hyZ2RkVjlNWW5CcFluQlNJeHc5UVZJRlBrQTNlZ1dyZUVMMVVsVnROTCs5cFZMc3hXd2JvRVxucGNLMFduOS9vd0lIakpJb0hXdzNhWnc0Wk5taFdVTWZ5OTRTMC9xaFhlcFczU3JZRlZjT0Z1alJBb0dBTmxkQ1xuOEJtcWw1d0RJL09CS2VTaGNyNTA0TW81QWRtN1ZIUXNMcnVFNUt6bkM0SndQaWw1dkpKZ2xoYlN4eFpTWHJEQVxuOUxPS0p1MFNIeGtQa3Bzb2lnQ3BjVC9qTGpDMEtkSmxnamVRbWVLblUxQjZSK29Xc25obUFVVlJLVFMzVklwdlxueDc2VnpWeEhUMDA1SjV2NkRvZE9MZVJVNjBUZG44V3VGQklQNjFFQ2dZQUlaQVFWc0YzTGk3WTRxemVtREJLSFxuWkdaMi9EMnF0TldUUXNDdXlqVnpBKzlqdzA1b3FsRy9KUmtYTHM1QzV4dVduZWYzczFJbHRPVjlPMk1sdnlXSlxuU0tRSWxET091NXRxaWdwOTBiYzF6MHFHY05XSmlMTmlwSS9tbnVXdkM3NDR3SGtpWWdpSXRiWE50c3dVdkZldVxuSzh6RHpxeHRDN2YreGdRYlZlTlFQQT09XG4tLS0tLUVORCBQUklWQVRFIEtFWS0tLS0tXG4iLAogICJjbGllbnRfZW1haWwiOiAiZGUtcHJvamVjdEBwZXJmZWN0LWRheS00Mzc4MDItcTUuaWFtLmdzZXJ2aWNlYWNjb3VudC5jb20iLAogICJjbGllbnRfaWQiOiAiMTA4NDU0MTEyMzU0MDE5NTA1ODE3IiwKICAiYXV0aF91cmkiOiAiaHR0cHM6Ly9hY2NvdW50cy5nb29nbGUuY29tL28vb2F1dGgyL2F1dGgiLAogICJ0b2tlbl91cmkiOiAiaHR0cHM6Ly9vYXV0aDIuZ29vZ2xlYXBpcy5jb20vdG9rZW4iLAogICJhdXRoX3Byb3ZpZGVyX3g1MDlfY2VydF91cmwiOiAiaHR0cHM6Ly93d3cuZ29vZ2xlYXBpcy5jb20vb2F1dGgyL3YxL2NlcnRzIiwKICAiY2xpZW50X3g1MDlfY2VydF91cmwiOiAiaHR0cHM6Ly93d3cuZ29vZ2xlYXBpcy5jb20vcm9ib3QvdjEvbWV0YWRhdGEveDUwOS9kZS1wcm9qZWN0JTQwcGVyZmVjdC1kYXktNDM3ODAyLXE1LmlhbS5nc2VydmljZWFjY291bnQuY29tIiwKICAidW5pdmVyc2VfZG9tYWluIjogImdvb2dsZWFwaXMuY29tIgp9Cg=="  # Replace with your real string

# Decode and use
creds_json = base64.b64decode(TEST_BASE64).decode("utf-8")
creds_dict = json.loads(creds_json)

# Verify the credentials
credentials = service_account.Credentials.from_service_account_info(creds_dict)
print("Service Account Email:", credentials.service_account_email)  # Should print your SA email

Service Account Email: de-project@perfect-day-437802-q5.iam.gserviceaccount.com

In [59]:
import pandas as pd
import geopandas as gpd
import osmnx as ox
from datetime import datetime
from datetime import timedelta
import pandas as pd
from shapely.geometry import Point, Polygon
from math import radians, sin, cos, sqrt, atan2
import numpy as np

In [60]:
# To display all rows without truncation
pd.set_option('display.max_rows', None)

# To also prevent column truncation
pd.set_option('display.max_columns', None)
pd.set_option('display.width', None)  # Auto-detect terminal width
pd.set_option('display.max_colwidth', None)  # Show full column content

In [61]:
stops_df = pd.read_csv("stops.csv")
trips_df = pd.read_csv("e_trips.csv")
stop_times_df = pd.read_csv("stop_times.csv")
filtered_pois_df = pd.read_csv("filtered_pois.csv")

In [135]:

'''
data transformation step:
'trip_id', 'arrival_time', 'departure_time', 'stop_id', 'stop_sequence',
       'pickup_type', 'drop_off_type', 'shape_dist_traveled', 'timepoint',
       'route_id', 'service_id', 'trip_headsign', 'direction_id', 'block_id',
       'shape_id', 'scheduled_trip_id', 'trip_short_name',
       'wheelchair_accessible', 'bikes_allowed', 'at_street',
       'corner_placement', 'heading', 'location_type', 'on_street',
       'parent_station', 'stop_code', 'stop_desc', 'stop_lat', 'stop_lon',
       'stop_name', 'stop_position', 'stop_timezone', 'stop_url',
       'wheelchair_boarding', 'zone_id'
final result
- trip_headsign
- bus number
- bus stop order
- bus direction? some way to differentiate direction
- stop lat/lon
- wheelchair boarding
- bikes_allowed
- arrival and departure time
'''

# Merge relevant data
merged_df = pd.merge(stop_times_df, trips_df, on='trip_id')
merged_df = pd.merge(merged_df, stops_df, on='stop_id')

merged_df = merged_df[['trip_id','arrival_time', 'departure_time', 'stop_sequence','trip_headsign', 'direction_id','route_id',
       'wheelchair_accessible', 'bikes_allowed', 'stop_lat', 'stop_lon',
       'stop_name']]
merged_df = merged_df.sort_values(by=['arrival_time', 'departure_time'])

all_unique_stops = merged_df.drop_duplicates(subset=[
    'stop_sequence',
    'trip_headsign',
    'direction_id',
    'route_id',
    'wheelchair_accessible',
    'bikes_allowed',
    'stop_lat',
    'stop_lon',
    'stop_name'
])

# Extract unique bus stops with their coordinates and bus numbers
# unique_stops_routes = merged_df[['route_id', 'stop_name', 'stop_lat', 'stop_lon']].drop_duplicates()
# unique_stops = unique_stops_routes[[ 'stop_name', 'stop_lat', 'stop_lon']].drop_duplicates()
all_unique_stops.head()

,trip_id,arrival_time,departure_time,stop_sequence,trip_headsign,direction_id,route_id,wheelchair_accessible,bikes_allowed,stop_lat,stop_lon,stop_name
410083,2736572_13819,04:16:00,04:16:00,1,7 William Cannon SB,0,7,1,1,30.338721,-97.719548,7072 Easy Wind/St Johns
46760,2726327_0637,04:17:00,04:17:00,1,10 Southpark Meadows SB,0,10,1,1,30.340202,-97.691345,Norwood Transit Center - A
410084,2736572_13819,04:17:47,04:17:47,2,7 William Cannon SB,0,7,1,1,30.336202,-97.718247,6904 Airport/Lamar
46761,2726327_0637,04:18:28,04:18:28,2,10 Southpark Meadows SB,0,10,1,1,30.340454,-97.690058,1113 Rutherford/Furness
410085,2736572_13819,04:18:52,04:18:52,3,7 William Cannon SB,0,7,1,1,30.333155,-97.716673,Airport/Guadalupe

In [136]:
# Step 1: Get the max stop_sequence per bus and bus direction
trip_dir_max_seq = (
    all_unique_stops
    .groupby(['route_id', 'direction_id', 'trip_id'])['stop_sequence']
    .max()
    .reset_index()
    .rename(columns={'stop_sequence': 'max_stop'})
)

trip_dir_max_seq.head(10)

   route_id  direction_id       trip_id  max_stop
0         1             0  2726088_0110        76
1         1             1  2726131_0001        18
2         1             1  2726197_0039        75
3         2             0  2727334_1598        33
4         2             1  2727408_1461        32
5         3             0  2729077_3326        95
6         3             1  2729133_3220        96
7         4             0  2733639_7963        18
8         4             0  2733650_7961        18
9         4             0  2733654_8026        25

In [137]:
# Step 3: Merge to get trip + route + max stop_sequence
trip_route_seq = pd.merge(trip_dir_max_seq, all_unique_stops, on='trip_id')
# Step 2: Drop the unwanted columns and rename
trip_route_seq = trip_route_seq.drop(columns=['direction_id_y', 'route_id_y']).rename(columns={'direction_id_x': 'direction_id', 'route_id_x': 'route_id'})  # Rename "_x" to original

In [138]:
trip_route_seq[trip_route_seq['stop_name'] == '10051 Great Hills/Research (Target)']

,route_id,direction_id,trip_id,max_stop,arrival_time,departure_time,stop_sequence,trip_headsign,wheelchair_accessible,bikes_allowed,stop_lat,stop_lon,stop_name
216,3,0,2729077_3326,95,05:02:00,05:02:00,1,3 Southpark Meadows SB,1,1,30.393337,-97.743545,10051 Great Hills/Research (Target)
406,3,1,2729133_3220,96,06:35:00,06:35:00,96,3 Arboretum NB,1,1,30.393337,-97.743545,10051 Great Hills/Research (Target)
3639,383,1,2733240_7311,41,06:01:01,06:01:01,28,383 North Lamar Transit Center SB,1,1,30.393337,-97.743545,10051 Great Hills/Research (Target)
3660,383,1,2744409_7426,21,13:34:01,13:34:01,8,383 North Lamar Transit Center SB,1,1,30.393337,-97.743545,10051 Great Hills/Research (Target)

In [140]:
# Step 4: Find the trip with the highest stop_sequence per route
longest_trips = (
    trip_route_seq
    .sort_values('max_stop', ascending=False)  # Sort to prioritize trips with highest max_stop
    .drop_duplicates(['route_id', 'trip_headsign', 'direction_id'], keep='first')  # Keep first occurrence (longest)
    ['trip_id']  # Optional: Keep only needed columns
)

In [141]:
# Step 5: Filter the original DataFrame to keep only these trips
all_unique_stops = all_unique_stops[all_unique_stops['trip_id'].isin(longest_trips)]

all_unique_stops.head()

,trip_id,arrival_time,departure_time,stop_sequence,trip_headsign,direction_id,route_id,wheelchair_accessible,bikes_allowed,stop_lat,stop_lon,stop_name
410083,2736572_13819,04:16:00,04:16:00,1,7 William Cannon SB,0,7,1,1,30.338721,-97.719548,7072 Easy Wind/St Johns
46760,2726327_0637,04:17:00,04:17:00,1,10 Southpark Meadows SB,0,10,1,1,30.340202,-97.691345,Norwood Transit Center - A
410084,2736572_13819,04:17:47,04:17:47,2,7 William Cannon SB,0,7,1,1,30.336202,-97.718247,6904 Airport/Lamar
46761,2726327_0637,04:18:28,04:18:28,2,10 Southpark Meadows SB,0,10,1,1,30.340454,-97.690058,1113 Rutherford/Furness
410085,2736572_13819,04:18:52,04:18:52,3,7 William Cannon SB,0,7,1,1,30.333155,-97.716673,Airport/Guadalupe

In [142]:
all_unique_stops[all_unique_stops['stop_name'] == '10051 Great Hills/Research (Target)']

,trip_id,arrival_time,departure_time,stop_sequence,trip_headsign,direction_id,route_id,wheelchair_accessible,bikes_allowed,stop_lat,stop_lon,stop_name
145831,2729077_3326,05:02:00,05:02:00,1,3 Southpark Meadows SB,0,3,1,1,30.393337,-97.743545,10051 Great Hills/Research (Target)
305599,2733240_7311,06:01:01,06:01:01,28,383 North Lamar Transit Center SB,1,383,1,1,30.393337,-97.743545,10051 Great Hills/Research (Target)
135750,2729133_3220,06:35:00,06:35:00,96,3 Arboretum NB,1,3,1,1,30.393337,-97.743545,10051 Great Hills/Research (Target)

In [143]:
# Define your specific location coordinates (latitude and longitude)
user_latitude = 30.393258 # Replace with your actual latitude 
user_longitude = -97.75583  # Replace with your actual longitude

# Calculate distances using Haversine formula
def haversine(lat1, lon1, lat2, lon2):
    R = 6371  # Radius of the Earth in kilometers
    dlat = radians(lat2 - lat1)
    dlon = radians(lon2 - lon1)
    a = sin(dlat / 2) ** 2 + cos(radians(lat1)) * cos(radians(lat2)) * sin(dlon / 2) ** 2
    c = 2 * atan2(sqrt(a), sqrt(1 - a))
    distance = R * c
    return distance

# Calculate distances for each bus stop
all_unique_stops['distance'] = all_unique_stops.apply(lambda row: haversine(user_latitude, user_longitude, row['stop_lat'], row['stop_lon']), axis=1)

# Sort bus stops by distance and get the closest stops
closest_stops = all_unique_stops.nsmallest(3, 'distance')[[ 'stop_name', 'stop_lat', 'stop_lon', 'distance']]

# Sort by distance (ascending) to prioritize closer stops
sorted_stops = all_unique_stops.sort_values('distance')

# Drop duplicates, keeping the first (closest) occurrence of each stop_name
unique_sorted_stops = sorted_stops.drop_duplicates(subset=['stop_name'], keep='first')

# Take the top 3 closest unique stops
closest_stops = unique_sorted_stops.head(3)[['stop_name', 'stop_lat', 'stop_lon', 'distance']]

# select the 3 closest bus stops
origin_stops = all_unique_stops[all_unique_stops['stop_name'].isin(closest_stops['stop_name'])]

origin_stops = origin_stops.sort_values(by='route_id')
origin_stops['distance'] = (np.ceil(origin_stops['distance']*100 ) * 10).astype(int)
origin_stops = origin_stops.rename(columns={'distance': 'distance (m)'})

# tag the closest stops to be origin stops
origin_stops['origin stop'] = True
origin_stops

,trip_id,arrival_time,departure_time,stop_sequence,trip_headsign,direction_id,route_id,wheelchair_accessible,bikes_allowed,stop_lat,stop_lon,stop_name,distance (m),origin stop
135748,2729133_3220,06:32:30,06:32:30,94,3 Arboretum NB,1,3,1,1,30.396981,-97.750138,10300 Jollyville/Great Hills,690,True
299164,2733194_7160,05:21:00,05:21:00,16,383 Lakeline Station NB,0,383,1,1,30.394273,-97.748666,9828 Great Hills/Research,700,True
299165,2733194_7160,05:21:35,05:21:35,17,383 Lakeline Station NB,0,383,1,1,30.395978,-97.749877,10201 Jollyville/Great Hills,650,True
305597,2733240_7311,05:59:01,05:59:01,26,383 North Lamar Transit Center SB,1,383,1,1,30.396981,-97.750138,10300 Jollyville/Great Hills,690,True
304535,2744392_7272,13:39:00,13:39:00,17,383 PAVILION NB,0,383,1,1,30.394273,-97.748666,9828 Great Hills/Research,700,True
304536,2744392_7272,13:39:35,13:39:35,18,383 PAVILION NB,0,383,1,1,30.395978,-97.749877,10201 Jollyville/Great Hills,650,True
463107,2738762_15153,06:38:05,06:38:05,3,982 Downtown/University of Texas SB,0,982,1,1,30.396981,-97.750138,10300 Jollyville/Great Hills,690,True
463045,2738767_15148,16:17:00,16:17:00,11,982 Pavillion Park & Ride NB,1,982,1,1,30.394273,-97.748666,9828 Great Hills/Research,700,True

In [ ]:
'''

Test suite

geting unique routes
    check if final data set has at least one of each bus
    check if each route's stop sequence is the max stop sequence
    
getting closest stops
    check if its only 3 stop names
    


'''

In [144]:

# initialize subsequent stops dataframe
subsequent_stops = pd.DataFrame()

for index,row in origin_stops.iterrows():
    # take the stop name and the stop sequence in order to find out which are the subsequent stops
    current_sequence = row['stop_sequence']
    headsign = row['trip_headsign']
    subsequent_stops_add = all_unique_stops[(all_unique_stops['stop_sequence'] > current_sequence) & (all_unique_stops['trip_headsign'] == headsign)]
    
    subsequent_stops = pd.concat([subsequent_stops,subsequent_stops_add])
    
subsequent_stops['origin stop'] = False

In [145]:
origin_stops

,trip_id,arrival_time,departure_time,stop_sequence,trip_headsign,direction_id,route_id,wheelchair_accessible,bikes_allowed,stop_lat,stop_lon,stop_name,distance (m),origin stop
135748,2729133_3220,06:32:30,06:32:30,94,3 Arboretum NB,1,3,1,1,30.396981,-97.750138,10300 Jollyville/Great Hills,690,True
299164,2733194_7160,05:21:00,05:21:00,16,383 Lakeline Station NB,0,383,1,1,30.394273,-97.748666,9828 Great Hills/Research,700,True
299165,2733194_7160,05:21:35,05:21:35,17,383 Lakeline Station NB,0,383,1,1,30.395978,-97.749877,10201 Jollyville/Great Hills,650,True
305597,2733240_7311,05:59:01,05:59:01,26,383 North Lamar Transit Center SB,1,383,1,1,30.396981,-97.750138,10300 Jollyville/Great Hills,690,True
304535,2744392_7272,13:39:00,13:39:00,17,383 PAVILION NB,0,383,1,1,30.394273,-97.748666,9828 Great Hills/Research,700,True
304536,2744392_7272,13:39:35,13:39:35,18,383 PAVILION NB,0,383,1,1,30.395978,-97.749877,10201 Jollyville/Great Hills,650,True
463107,2738762_15153,06:38:05,06:38:05,3,982 Downtown/University of Texas SB,0,982,1,1,30.396981,-97.750138,10300 Jollyville/Great Hills,690,True
463045,2738767_15148,16:17:00,16:17:00,11,982 Pavillion Park & Ride NB,1,982,1,1,30.394273,-97.748666,9828 Great Hills/Research,700,True

In [146]:
all_possible_stops = pd.concat([origin_stops,subsequent_stops])

In [147]:
all_possible_stops['route_id'].unique()

array([  3, 383, 982])

In [148]:
import math
from shapely import wkt

# Define a function to convert each polygon to its centroid point
def get_centroid(geom):
    return Point(geom.centroid)


'''
Gets specific list of POIs that are within walking distance of the bus stops and produces a map.html image that user can interact with
Uses a pre downloaded POI list loaded from GCS

If there are overlapping POIs, algorithm will select whichever is closest to the bus stop

Arguments:
    - filtered_pois_df: list of amenities that I think might be interesting to go to/visit
    - possible_locations: dataframe of bus_stops that user is able to go to

Returns:
    - combined_poi: dataframe of all POIs that user can go to 

Notes:
    - folium icon list: https://fontawesome.com/v4/icons/
'''

# Step 1: Add a geometry column to the bus stop DataFrame
possible_locations = all_possible_stops.copy()
possible_locations.loc[:, 'geometry'] = possible_locations.apply(
    lambda row: Point(row['stop_lon'], row['stop_lat']),
    axis=1
)    

# First ensure the geometry column is string type
filtered_pois_df['geometry'] = filtered_pois_df['geometry'].astype(str)

# Step 2: Convert both DataFrames to GeoDataFrames
# Set the CRS to WGS84 (EPSG:4326) for latitude/longitude
filtered_pois_df['geometry'] = filtered_pois_df['geometry'].apply(wkt.loads)

bus_stops_gdf = gpd.GeoDataFrame(possible_locations, geometry='geometry', crs='EPSG:4326')
pois_gdf = gpd.GeoDataFrame(filtered_pois_df, geometry='geometry', crs='EPSG:4326')

# Separate points and polygons
points_gdf = pois_gdf[pois_gdf.geometry.type == 'Point']
polygons_gdf = pois_gdf[pois_gdf.geometry.type == 'Polygon']

# Step 3: Create a copy for buffered bus stops
bus_stops_buffered_gdf = bus_stops_gdf.copy()

# Step 4: Calculate buffer distance in degrees
def meters_to_degrees(meters, latitude):
    return meters / (111320 * math.cos(math.radians(latitude)))

buffer_distance_degrees = meters_to_degrees(500, 30.26562)  # 500 meters at latitude 30.26562

# Step 5: Apply buffer to create circular areas around bus stops
bus_stops_buffered_gdf['geometry'] = bus_stops_buffered_gdf.geometry.buffer(buffer_distance_degrees)

# Step 6: Perform a spatial join to find POIs within the buffered area
pois_within_500m_points = gpd.sjoin(points_gdf,bus_stops_buffered_gdf,how='inner',predicate='within')
pois_within_500m_poly = gpd.sjoin(polygons_gdf, bus_stops_buffered_gdf, how='inner', predicate='intersects')

# Calculate for centroid
pois_within_500m_poly['geometry'] = pois_within_500m_poly['geometry'].centroid

combined_poi = pd.concat([pois_within_500m_poly, pois_within_500m_points], ignore_index=True)


# Removing duplicate POIs

# Extract coordinates from geometry and stop_lat/stop_lon
combined_poi['distance'] = combined_poi.apply(
    lambda row: haversine(
        row.geometry.x, row.geometry.y,  # POI coordinates (lon, lat)
        row['stop_lon'], row['stop_lat']  # Bus stop coordinates
    ),
    axis=1
)

# Sort by distance (ascending) to prioritize shortest distances
combined_poi = combined_poi.sort_values('distance')

# Drop duplicates, keeping the closest POI per geometry
combined_poi = combined_poi.drop_duplicates(subset=['geometry'], keep='first')

C:\Users\Martin\AppData\Local\Temp\ipykernel_38148\3096250227.py:57: UserWarning: Geometry is in a geographic CRS. Results from 'buffer' are likely incorrect. Use 'GeoSeries.to_crs()' to re-project geometries to a projected CRS before this operation.

  bus_stops_buffered_gdf['geometry'] = bus_stops_buffered_gdf.geometry.buffer(buffer_distance_degrees)
C:\Users\Martin\AppData\Local\Temp\ipykernel_38148\3096250227.py:64: UserWarning: Geometry is in a geographic CRS. Results from 'centroid' are likely incorrect. Use 'GeoSeries.to_crs()' to re-project geometries to a projected CRS before this operation.

  pois_within_500m_poly['geometry'] = pois_within_500m_poly['geometry'].centroid

In [149]:
combined_poi = combined_poi.merge(origin_stops[['trip_headsign','stop_name','stop_sequence']], how = 'left', on = 'trip_headsign')

combined_poi = combined_poi.rename(columns={'stop_name_x': 'stop_name',
                                            'stop_name_y': 'origin_stop',
                                            'stop_sequence_x': 'stop_sequence',
                                            'stop_sequence_y': 'first_stop_number'})

In [150]:
combined_poi.head()

,amenity,name,geometry,icon,color,index_right,trip_id,arrival_time,departure_time,stop_sequence,trip_headsign,direction_id,route_id,wheelchair_accessible,bikes_allowed,stop_lat,stop_lon,stop_name,distance (m),origin stop,distance,origin_stop,first_stop_number
0,cafe,Starbucks,POINT (-97.72227 30.39087),coffee,green,305603,2733240_7311,06:07:08,06:07:08,32,383 North Lamar Transit Center SB,1,383,1,1,30.391127,-97.722228,Braker/Burnet SW Corner,NaN,False,0.006076,10300 Jollyville/Great Hills,26
1,restaurant,Twin Lion,POINT (-97.74802 30.4001),cutlery,green,299166,2733194_7160,05:22:50,05:22:50,18,383 Lakeline Station NB,0,383,1,1,30.400576,-97.748014,4815 Braker/Jollyville,NaN,False,0.007148,9828 Great Hills/Research,16
2,restaurant,Twin Lion,POINT (-97.74802 30.4001),cutlery,green,299166,2733194_7160,05:22:50,05:22:50,18,383 Lakeline Station NB,0,383,1,1,30.400576,-97.748014,4815 Braker/Jollyville,NaN,False,0.007148,10201 Jollyville/Great Hills,17
3,restaurant,Dollar Slice Club,POINT (-97.74193 30.2866),cutlery,green,463111,2738762_15153,06:59:13,06:59:13,7,982 Downtown/University of Texas SB,0,982,1,1,30.286064,-97.741815,UT West Mall Station (SB),NaN,False,0.015288,10300 Jollyville/Great Hills,3
4,place_of_worship,Anderson Mill Baptist Church,POINT (-97.8038 30.45629),institution,orange,299185,2733194_7160,05:49:00,05:49:00,37,383 Lakeline Station NB,0,383,1,1,30.455338,-97.803750,12221 Millwright/Wendts Way,NaN,False,0.015457,9828 Great Hills/Research,16

In [152]:
all_possible_stops.head()

,trip_id,arrival_time,departure_time,stop_sequence,trip_headsign,direction_id,route_id,wheelchair_accessible,bikes_allowed,stop_lat,stop_lon,stop_name,distance (m),origin stop,distance
135748,2729133_3220,06:32:30,06:32:30,94,3 Arboretum NB,1,3,1,1,30.396981,-97.750138,10300 Jollyville/Great Hills,690.0,True,NaN
299164,2733194_7160,05:21:00,05:21:00,16,383 Lakeline Station NB,0,383,1,1,30.394273,-97.748666,9828 Great Hills/Research,700.0,True,NaN
299165,2733194_7160,05:21:35,05:21:35,17,383 Lakeline Station NB,0,383,1,1,30.395978,-97.749877,10201 Jollyville/Great Hills,650.0,True,NaN
305597,2733240_7311,05:59:01,05:59:01,26,383 North Lamar Transit Center SB,1,383,1,1,30.396981,-97.750138,10300 Jollyville/Great Hills,690.0,True,NaN
304535,2744392_7272,13:39:00,13:39:00,17,383 PAVILION NB,0,383,1,1,30.394273,-97.748666,9828 Great Hills/Research,700.0,True,NaN

In [154]:
import folium

# Create a Folium map centered on a specific location
lat = 30.395058010232503
lon = -97.75364638639988
map = folium.Map(location=[lat, lon], zoom_start=12)

# Adding home

# Adding bus stops
for index, row in all_possible_stops.iterrows():
    poi_lat = row['stop_lat']
    poi_lon = row['stop_lon']
    stop = row['stop_name']
    headsign = row['trip_headsign']
    
    popup_text = folium.Html(f"Bus Station: {stop} heading towards {headsign}", script = True)
    
    # Add a marker for each row to the map
    folium.Marker(
        location = [poi_lat, poi_lon], 
        popup=folium.Popup(popup_text, parse_html=True, max_width=300),
        icon=folium.Icon(color='black' ,icon='bus', prefix='fa')).add_to(map)

# Iterate over the rows of the DataFrame
for index, row in combined_poi.iterrows():
    poi_lat = row.geometry.y
    poi_lon = row.geometry.x
    poi_busstop = str(row['stop_name'])
    poi_bus = row['route_id']
    poi_name = row['name']
    num_stops = row['stop_sequence'] - row['first_stop_number']
    poi_amenity = row['amenity']
    icon_name = row['icon']
    icon_color = row['color']
    # print(f'printing {poi_name}')
    
    popup_text = folium.Html(f"Take bus {poi_bus} for {num_stops} stops <br> Closest bus stop: {poi_busstop}.<br>Name of POI: {poi_name}.<br>Type of POI: {poi_amenity}.<br>.", script = True)

    # Add a marker for each row to the map
    folium.Marker(
        location = [poi_lat, poi_lon], 
        popup=folium.Popup(popup_text, parse_html=True, max_width=300),
        icon=folium.Icon(color=icon_color ,icon=icon_name, prefix='fa')).add_to(map)
    
folium.Marker(
location = [lat, lon], 
popup='Home',
icon=folium.Icon(color='green' ,icon='home', prefix='fa')).add_to(map)

display(map)

In [ ]:
def bus_n_stops_finder(merged_df,):


    # Define your specific location coordinates (latitude and longitude)
    user_latitude = 30.393258 # Replace with your actual latitude 
    user_longitude = -97.75583  # Replace with your actual longitude

    # Calculate distances using Haversine formula
    def haversine(lat1, lon1, lat2, lon2):
        R = 6371  # Radius of the Earth in kilometers
        dlat = radians(lat2 - lat1)
        dlon = radians(lon2 - lon1)
        a = sin(dlat / 2) ** 2 + cos(radians(lat1)) * cos(radians(lat2)) * sin(dlon / 2) ** 2
        c = 2 * atan2(sqrt(a), sqrt(1 - a))
        distance = R * c
        return distance

    # Calculate distances for each bus stop
    merged_df['distance'] = merged_df.apply(lambda row: haversine(user_latitude, user_longitude, row['stop_lat'], row['stop_lon']), axis=1)

    # Sort bus stops by distance and get the closest stops
    closest_stops = merged_df.nsmallest(3, 'distance')[[ 'stop_name', 'stop_lat', 'stop_lon', 'distance']]

    # Print or use the closest bus stops
    top3_stops = closest_stops['stop_name']

    # select the 3 closest bus stops
    bus_n_stops = merged_df[merged_df['stop_name'].isin(top3_stops)]

    bus_n_stops = bus_n_stops.sort_values(by='route_id')
    bus_n_stops['distance'] = (np.ceil(bus_n_stops['distance']*100 ) * 10).astype(int)
    bus_n_stops = bus_n_stops.rename(columns={'distance': 'distance (m)'})
    
    # tag the closest stops to be origin stops
    bus_n_stops['origin stops'] = True
    
    subsequent_stops =
    
    return bus_n_stops

def real_bus_origin(unique_stops_df, origin):
    '''
    Because the bus origin might change depending on the time the user departs, it is important to choose the user's bus
    stop correctly.

    Inputs:
    - unique_stops_df: DataFrame containing all stop times and locations of the selected bus.
    - origin: The stop name where the user intends to start (selected on stops.html).

    Output:
    - The time-appropriate bus stop (first stop after or equal to the user's origin).
    '''

    # Extract the stop_sequence as a single integer
    current_sequence = unique_stops_df[unique_stops_df['stop_name'] == origin]['stop_sequence'].iloc[0]
    print(current_sequence)  # Debugging: Check the extracted value

    # Find the first stop where stop_sequence >= current_sequence
    possible_locations = unique_stops_df[unique_stops_df['stop_sequence'] >= current_sequence]

    return possible_locations

In [ ]:
def bus_stops_finder(bus_number, unique_stops_df ):
    '''
    This function finds all available bus stops based on a bus number

    Inputs: 
    - bus_number (integer): Bus number 
    - unique_stops_df: dataframe of trips.txt from GTFS data
    - stops_df: dataframe of stops.txt from GTFS data
    - stop_times_df: dataframe of stops_times.txt from GTFS data

    Outputs:
    - unique_stops: Array of unique bus stops in that bus line
    - stops_times_location_df: dataframe of the unique stops for that bus line

    '''

    route_trips = unique_stops_df[unique_stops_df['route_id'].isin([bus_number])]

    bus_trip_id= route_trips[['trip_id','direction_id']]

    # Using the bus IDs, we can filter out the stop times for each bus unqiue bus route with the stop_times_df
    selected_stop_times = stop_times_df[stop_times_df['trip_id'].isin(bus_trip_id['trip_id'])]
    selected_stop_times = selected_stop_times.merge(bus_trip_id, on="trip_id")

    # merge into one dataframe so we can get the bus locations and bus timings
    selected_stops_times_location = selected_stop_times.merge(stops_df[['stop_name', 'stop_lat', 'stop_lon','stop_id']], on='stop_id', how='inner')

    # get unique stops to display for user
    unique_stops = selected_stops_times_location['stop_name'].unique()

    unique_stops = unique_stops.tolist()

    return unique_stops, selected_stops_times_location

C:\Users\Martin\AppData\Local\Temp\ipykernel_74664\3239314869.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  merged_df['distance'] = merged_df.apply(lambda row: haversine(user_latitude, user_longitude, row['stop_lat'], row['stop_lon']), axis=1)

,arrival_time,departure_time,stop_sequence,trip_headsign,direction_id,route_id,wheelchair_accessible,bikes_allowed,stop_lat,stop_lon,stop_name,distance (m)
135748,06:32:30,06:32:30,94,3 Arboretum NB,1,3,1,1,30.396981,-97.750138,10300 Jollyville/Great Hills,690
299165,05:21:35,05:21:35,17,383 Lakeline Station NB,0,383,1,1,30.395978,-97.749877,10201 Jollyville/Great Hills,650
304266,18:41:39,18:41:39,18,383 PAVILION NB,0,383,1,1,30.395978,-97.749877,10201 Jollyville/Great Hills,650
305597,05:59:01,05:59:01,26,383 North Lamar Transit Center SB,1,383,1,1,30.396981,-97.750138,10300 Jollyville/Great Hills,690
309841,18:33:49,18:33:49,6,383 North Lamar Transit Center SB,1,383,1,1,30.396981,-97.750138,10300 Jollyville/Great Hills,690
463107,06:38:05,06:38:05,3,982 Downtown/University of Texas SB,0,982,1,1,30.396981,-97.750138,10300 Jollyville/Great Hills,690

In [51]:
def bus_stops_finder(bus_number, trips_df, stops_df,stop_times_df ):
    '''
    This function finds all available bus stops based on a bus number

    Inputs: 
    - bus_number (integer): Bus number 
    - trips_df: dataframe of trips.txt from GTFS data
    - stops_df: dataframe of stops.txt from GTFS data
    - stop_times_df: dataframe of stops_times.txt from GTFS data

    Outputs:
    - unique_stops: Array of unique bus stops in that bus line
    - stops_times_location_df: dataframe of the unique stops for that bus line

    '''

    route_trips = trips_df[trips_df['route_id'].isin([bus_number])]

    # By getting the unique trip headsigns we can get a trip_id that is associate to the unique trips the bus makes. A bus makes multiple duplicate trips throughout the day, but the trip_headsign remains the same
    unique_rows = route_trips.drop_duplicates(subset='trip_headsign')

    bus_trip_id= unique_rows[['trip_id','direction_id']]

    # Using the bus IDs, we can filter out the stop times for each bus unqiue bus route with the stop_times_df
    selected_stop_times = stop_times_df[stop_times_df['trip_id'].isin(bus_trip_id['trip_id'])]
    selected_stop_times = selected_stop_times.merge(bus_trip_id, on="trip_id")

    # merge into one dataframe so we can get the bus locations and bus timings
    selected_stops_times_location = selected_stop_times.merge(stops_df[['stop_name', 'stop_lat', 'stop_lon','stop_id']], on='stop_id', how='inner')

    # get unique stops to display for user
    unique_stops = selected_stops_times_location['stop_name'].unique()

    unique_stops = unique_stops.tolist()

    return unique_stops, selected_stops_times_location



def real_bus_origin(unique_stops_df, origin):
    '''
    Because the bus origin might change depending on the time the user departs, it is important to choose the user's bus
    stop correctly.

    Inputs:
    - unique_stops_df: DataFrame containing all stop times and locations of the selected bus.
    - origin: The stop name where the user intends to start (selected on stops.html).

    Output:
    - The time-appropriate bus stop (first stop after or equal to the user's origin).
    '''

    # Extract the stop_sequence as a single integer
    current_sequence = unique_stops_df[unique_stops_df['stop_name'] == origin]['stop_sequence'].iloc[0]
    print(current_sequence)  # Debugging: Check the extracted value

    # Find the first stop where stop_sequence >= current_sequence
    possible_locations = unique_stops_df[unique_stops_df['stop_sequence'] >= current_sequence]

    return possible_locations

# Define a function to convert each polygon to its centroid point
def get_centroid(geom):
    return Point(geom.centroid)

def POI_getter(amenities, possible_locations):

    '''
    color scheme

    food: green
    community stuff: brown
    leisure: blue

    folium icon list: https://fontawesome.com/v4/icons/
    '''
    amenities_of_interest = {
        # food
        'cafe':['coffee','brown'],'bar':['beer','brown'],'restaurant':['cutlery','brown'],'pub':['beer','brown'],

        
        # social buildings
        'social_centre':['institution','blue'],'library':['book','blue'],'marketplace':['shopping-cart','blue'],
        'events_venue':['institution','blue'],'exhibition_centre':['institution','blue'],'place_of_worship':['institution','blue'],

        # places to chill
        'park' :['tree','green'],'music_venue':['music', 'black'],'cinema':['film','blue'],'theatre':['film','blue']

        # transportation
    }

    # Define amenities of interest
    amenities = list(amenities_of_interest.keys())
    amenity_tags = {'amenity': amenities}
    building_tags = {"building": "train_station"}


    # Create an empty DataFrame to store POIs
    poi_df = pd.DataFrame()

    # Iterate through the DataFrame
    for index, row in possible_locations.iterrows():
        latitude = row['stop_lat']
        longitude = row['stop_lon']
        center_point = (latitude,longitude)
        tags = {'amenity': amenities}

        # change the distance!
        try:
            G = ox.features_from_point(center_point, tags={**amenity_tags, **building_tags}, dist=200)
            G['busstop'] = row['stop_name'] 
            poi_df = pd.concat([poi_df, G], ignore_index=True)
        except ox._errors.InsufficientResponseError as e:
            pass
        
    # Filter the geodataframe based on the condition
    poi_df[['icon','color']] = poi_df['amenity'].apply(lambda x: pd.Series(amenities_of_interest[x]) if x in amenities_of_interest else pd.Series([None, None]))
    

    # Apply the function to the geometry column and create a new column of points
    poi_df['points'] = poi_df['geometry'].apply(get_centroid)
    # Display the resulting DataFrame with POIs
    return poi_df


def transit_duration(origin, destination, location_df):
    # get the bus timings
    get_on = location_df[location_df['stop_name'] == origin]['departure_time'].values[0]
    get_off = location_df[location_df['stop_name'] == destination]['departure_time'].values[0]

    # calculate the time difference
    start_time = datetime.strptime(get_on, '%H:%M:%S')
    user_time = datetime.strptime(get_off, '%H:%M:%S')

    time_diff = user_time - start_time
    time_diff_mins = time_diff.total_seconds() / 60

    return time_diff_mins

def map_maker(origin_stop, lat,lon,all_busstops, poi_df, stop_times_df):
    # Create a Folium map centered on a specific location
    map = folium.Map(location=[lat, lon], zoom_start=12)

    # Adding home
    
    # Adding bus stops
    for index, row in all_busstops.iterrows():
        poi_lat = row['stop_lat']
        poi_lon = row['stop_lon']
        
        # Add a marker for each row to the map
        folium.Marker(
            location = [poi_lat, poi_lon], 
            # popup=folium.Popup(popup_text, parse_html=True, max_width=300),
            icon=folium.Icon(color='black' ,icon='bus', prefix='fa')).add_to(map)

    # Iterate over the rows of the DataFrame
    for index, row in poi_df.iterrows():
        poi_lat = row.points.y
        poi_lon = row.points.x
        poi_busstop = str(row['busstop'])
        poi_name = row['name']
        poi_amenity = row['amenity']
        icon_name = row['icon']
        icon_color = row['color']
        time = transit_duration(origin_stop,poi_busstop,stop_times_df)
        # print(f'printing {poi_name}')
        
        popup_text = folium.Html(f"Closest bus stop: {poi_busstop}.<br>Name of POI: {poi_name}.<br>Type of POI: {poi_amenity}.<br>Bus journey: {time}.", script = True)

        # Add a marker for each row to the map
        folium.Marker(
            location = [poi_lat, poi_lon], 
            popup=folium.Popup(popup_text, parse_html=True, max_width=300),
            icon=folium.Icon(color=icon_color ,icon=icon_name, prefix='fa')).add_to(map)
        
    folium.Marker(
    location = [lat, lon], 
    popup='Home',
    icon=folium.Icon(color='green' ,icon='home', prefix='fa')).add_to(map)

    display(map)
    # Display the map
    map.save('D:/Coding projects/Bus POI Finder/capmetro/templates/map.html')  # Save the map as an HTML file

In [ ]:


unique_stops, stops_times_location_df = bus_stops_finder(3, merged_df)
stops_times_location_df

TypeError: bus_stops_finder() missing 2 required positional arguments: 'stops_df' and 'stop_times_df'

In [53]:
unique_stops, stops_times_location_df = bus_stops_finder(3, trips_df, stops_df,stop_times_df)
all_busstops = real_bus_origin(stops_times_location_df,'Slaughter/Simonetti')
all_busstops

5

,trip_id,arrival_time,departure_time,stop_id,stop_sequence,pickup_type,drop_off_type,shape_dist_traveled,timepoint,direction_id,stop_name,stop_lat,stop_lon
4,2729133_3220,05:02:55,05:02:55,5416,5,0,0,1.2864,0,1,Slaughter/Simonetti,30.174173,-97.804467
5,2729133_3220,05:03:24,05:03:24,3766,6,0,0,1.4102,0,1,818 Slaughter/Palace,30.174142,-97.806358
6,2729133_3220,05:04:11,05:04:11,2933,7,0,0,1.6161,0,1,Slaughter/United Kingdom,30.174099,-97.809607
7,2729133_3220,05:05:25,05:05:25,2934,8,0,0,1.9373,0,1,Slaughter/Texas Oaks,30.173995,-97.814789
8,2729133_3220,05:05:56,05:05:56,2935,9,0,0,2.0725,0,1,1312 Slaughter/Bilbrook,30.173971,-97.816864
...,...,...,...,...,...,...,...,...,...,...,...,...,...
186,2729077_3326,06:30:20,06:30:20,5999,91,0,0,22.5106,0,0,509 Slaughter/1st,30.171795,-97.798989
187,2729077_3326,06:31:19,06:31:19,5380,92,0,0,22.7985,0,0,404 Slaughter/Francia,30.168969,-97.795672
188,2729077_3326,06:32:03,06:32:03,5623,93,0,0,23.0095,0,0,236 Slaughter/Alice Mae,30.167354,-97.792824
189,2729077_3326,06:32:51,06:32:51,6322,94,0,0,23.2424,0,0,130 Slaughter/Congress,30.166994,-97.789102
190,2729077_3326,06:35:00,06:35:00,5263,95,0,0,23.8670,1,0,200 Turk/Cullen,30.163367,-97.791351

In [ ]:
bus = 3  # Try to convert input to a float

# Store the result in a session variable

result, stops_times_locations_df = bus_stops_finder(bus, trips_df, stops_df,stop_times_df)
        

bus_stop = "603 Slaughter/1st"

time = "16:58:00"

result, stops_times_locations_df = bus_stops_finder(bus, trips_df, stops_df,stop_times_df)
all_busstops = real_bus_origin(time,stops_times_locations_df,bus_stop)
amenities = ['restaurant', 'cafe', 'park','cinema','music_venue',
        'social_centre','theatre','marketplace']


POI_df = POI_getter(amenities,all_busstops)

# get lat, lng of original bus stop
lat = stops_times_locations_df[stops_times_locations_df['stop_name'] == bus_stop].iloc[0]['stop_lat']
lon = stops_times_locations_df[stops_times_locations_df['stop_name'] == bus_stop].iloc[0]['stop_lon']\

c:\Users\psle1\anaconda3\lib\site-packages\ipykernel\ipkernel.py:287: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)

In [16]:
stops_times_locations_df.iloc[4:10]

c:\Users\psle1\anaconda3\lib\site-packages\ipykernel\ipkernel.py:287: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)

,trip_id,arrival_time,departure_time,stop_id,stop_sequence,pickup_type,drop_off_type,shape_dist_traveled,timepoint,direction_id,stop_name,stop_lat,stop_lon
4,2729133_3220,05:01:43,05:01:43,6407,4,0,0,0.9725,0,1,603 Slaughter/1st,30.172829,-97.799722
5,2729133_3220,05:02:55,05:02:55,5416,5,0,0,1.2864,0,1,Slaughter/Simonetti,30.174173,-97.804467
6,2729133_3220,05:03:24,05:03:24,3766,6,0,0,1.4102,0,1,818 Slaughter/Palace,30.174142,-97.806358
7,2729133_3220,05:04:11,05:04:11,2933,7,0,0,1.6161,0,1,Slaughter/United Kingdom,30.174099,-97.809607
8,2729133_3220,05:05:25,05:05:25,2934,8,0,0,1.9373,0,1,Slaughter/Texas Oaks,30.173995,-97.814789
9,2729133_3220,05:05:56,05:05:56,2935,9,0,0,2.0725,0,1,1312 Slaughter/Bilbrook,30.173971,-97.816864

In [12]:
POI_df['building'].unique()

c:\Users\psle1\anaconda3\lib\site-packages\ipykernel\ipkernel.py:287: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)

array([nan, 'yes', 'retail', 'church', 'commercial'], dtype=object)

In [13]:
map_maker(bus_stop, lat,lon,all_busstops,POI_df,stops_times_locations_df)

<ipython-input-10-492a0ad1407d>:209: UserWarning: color argument of Icon should be one of: {'blue', 'lightblue', 'cadetblue', 'pink', 'darkred', 'gray', 'darkpurple', 'lightgreen', 'orange', 'darkblue', 'green', 'black', 'purple', 'red', 'white', 'lightred', 'darkgreen', 'beige', 'lightgray'}.
  icon=folium.Icon(color=icon_color ,icon=icon_name, prefix='fa')).add_to(map)

In [9]:
amenities_of_interest = {
        'cafe':['coffee','brown'],'bar':['beer','brown'],'restaurant':['cutlery','brown'],'pub':['beer','brown'],
        
        # social buildings
        'social_centre':['institution','blue'],'library':['book','blue'],'marketplace':['shopping-cart','blue'],'cinema':['film','blue'],
        'park' :['tree','green'],
        'music_venue':['music', 'black']

        # transportation
    }

amenities_of_interest

# key_list = list(my_dict.keys())
list(amenities_of_interest.keys())

['cafe',
 'bar',
 'restaurant',
 'pub',
 'social_centre',
 'library',
 'marketplace',
 'cinema',
 'park',
 'music_venue']