In [10]:
import osmnx as ox
import pandas as pd
import geopandas as gpd
from shapely.geometry import Point
from shapely.ops import nearest_points
import pyproj

In [ ]:
# Define the latitude and longitude of the center point
latitude = 30.280929678710276
longitude = -97.75218815500368

# Define the radius in meters (5 km = 5000 meters)
radius = 25000

# Define amenities of interest
amenities_of_interest = {
    # food
    'cafe': ['coffee', 'green'],
    'bar': ['beer', 'green'],
    'restaurant': ['cutlery', 'green'],
    'pub': ['beer', 'green'],

    # social buildings
    'social_centre': ['institution', 'orange'],
    'library': ['book', 'orange'],
    'marketplace': ['shopping-cart', 'green'],
    'events_venue': ['institution', 'orange'],
    'exhibition_centre': ['institution', 'lightgrey'],
    'place_of_worship': ['institution', 'orange'],

    # places to chill
    'park': ['tree', 'green'],
    'music_venue': ['music', 'red'],
    'cinema': ['film', 'red'],
    'theatre': ['film', 'red']
}

# Define amenities of interest
amenities = list(amenities_of_interest.keys())
amenity_tags = {'amenity': amenities}

# Query the POIs within the specified radius
pois = ox.geometries.geometries_from_point((latitude, longitude), tags=amenity_tags, dist=radius)

# Filter the POIs to include only the amenities of interest
filtered_pois = pois[pois['amenity'].isin(amenities)]

# Create a new DataFrame with selected columns
columns_to_keep = ['amenity', 'name', 'geometry']  # Add other columns if needed
filtered_pois_df = filtered_pois[columns_to_keep]

# Add a column for the icon and color based on the amenities_of_interest dictionary
filtered_pois_df['icon'] = filtered_pois_df['amenity'].apply(lambda x: amenities_of_interest[x][0])
filtered_pois_df['color'] = filtered_pois_df['amenity'].apply(lambda x: amenities_of_interest[x][1])

# Save the DataFrame to a CSV file

filtered_pois_df

C:\Users\psle1\AppData\Local\Temp\ipykernel_12572\3881686637.py:36: UserWarning: The `geometries` module and `geometries_from_X` functions have been renamed the `features` module and `features_from_X` functions. Use these instead. The `geometries` module and function names are deprecated and will be removed in a future release.
  pois = ox.geometries.geometries_from_point((latitude, longitude), tags=amenity_tags, dist=radius)
c:\Users\psle1\anaconda3\envs\bus_website\lib\site-packages\geopandas\geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
c:\Users\psle1\anaconda3\envs\bus_website\lib\site-packages\geopandas\geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)

                                 amenity                              name  \
element_type osmid
node         336605818               bar                 The Elephant Room
             338450996           theatre               The Hideout Theater
             338450997              cafe                         Starbucks
             338451013              cafe                         Starbucks
             355352958  place_of_worship                   San Jose Church
...                                  ...                               ...
relation     5700520    place_of_worship       Church of Conscious Harmony
             5700821    place_of_worship                               NaN
             5700911    place_of_worship          Hillcrest Baptist Church
             5713869    place_of_worship  Manchaca United Methodist Church
             10521767   place_of_worship             Christ Science Church

                                                                 geometry  \
element_type osmid
node         336605818                         POINT (-97.74350 30.26562)
             338450996                         POINT (-97.74223 30.26857)
             338450997                         POINT (-97.74297 30.26827)
             338451013                         POINT (-97.74118 30.27188)
             355352958                         POINT (-97.76334 30.24201)
...                                                                   ...
relation     5700520    POLYGON ((-97.84412 30.30748, -97.84418 30.307...
             5700821    POLYGON ((-97.66848 30.44399, -97.66844 30.443...
             5700911    POLYGON ((-97.74998 30.37397, -97.75001 30.373...
             5713869    POLYGON ((-97.83208 30.14015, -97.83210 30.140...
             10521767   POLYGON ((-97.74321 30.27663, -97.74321 30.276...

                               icon   color
element_type osmid
node         336605818         beer   green
             338450996         film     red
             338450997       coffee   green
             338451013       coffee   green
             355352958  institution  orange
...                             ...     ...
relation     5700520    institution  orange
             5700821    institution  orange
             5700911    institution  orange
             5713869    institution  orange
             10521767   institution  orange

[2595 rows x 5 columns]

## Data Transformation

In [14]:
unique_bus_stops = pd.read_csv("bus_stop_lat_lon.csv")
unique_bus_stops

,trip_id,arrival_time,departure_time,stop_id,stop_sequence,pickup_type,drop_off_type,shape_dist_traveled,timepoint,direction_id,stop_name,stop_lat,stop_lon
0,2729133_3220,04:58:00,04:58:00,5263,1,0,0,0.0000,1,1,200 Turk/Cullen,30.163367,-97.791351
1,2729133_3220,04:59:41,04:59:41,6479,2,0,0,0.4377,0,1,305 Slaughter/Alice Mae,30.167797,-97.793350
2,2729133_3220,05:00:27,05:00:27,5968,3,0,0,0.6388,0,1,324 Slaughter/Francia,30.169519,-97.795847
3,2729133_3220,05:01:43,05:01:43,6407,4,0,0,0.9725,0,1,603 Slaughter/1st,30.172829,-97.799722
4,2729133_3220,05:02:55,05:02:55,5416,5,0,0,1.2864,0,1,Slaughter/Simonetti,30.174173,-97.804467
...,...,...,...,...,...,...,...,...,...,...,...,...,...
184,2729077_3326,06:28:41,06:28:41,3767,90,0,0,22.0309,0,0,815 Slaughter/Palace,30.173859,-97.805997
185,2729077_3326,06:30:20,06:30:20,5999,91,0,0,22.5106,0,0,509 Slaughter/1st,30.171795,-97.798989
186,2729077_3326,06:31:19,06:31:19,5380,92,0,0,22.7985,0,0,404 Slaughter/Francia,30.168969,-97.795672
187,2729077_3326,06:32:03,06:32:03,5623,93,0,0,23.0095,0,0,236 Slaughter/Alice Mae,30.167354,-97.792824
188,2729077_3326,06:32:51,06:32:51,6322,94,0,0,23.2424,0,0,130 Slaughter/Congress,30.166994,-97.789102

In [15]:
# Remove rows where the 'name' column is NaN
filtered_pois_df = filtered_pois_df.dropna(subset=['name','amenity'])
filtered_pois_df

                                 amenity                              name  \
element_type osmid
node         336605818               bar                 The Elephant Room
             338450996           theatre               The Hideout Theater
             338450997              cafe                         Starbucks
             338451013              cafe                         Starbucks
             355352958  place_of_worship                   San Jose Church
...                                  ...                               ...
relation     5694381    place_of_worship  Memorial United Methodist Church
             5700520    place_of_worship       Church of Conscious Harmony
             5700911    place_of_worship          Hillcrest Baptist Church
             5713869    place_of_worship  Manchaca United Methodist Church
             10521767   place_of_worship             Christ Science Church

                                                                 geometry  \
element_type osmid
node         336605818                         POINT (-97.74350 30.26562)
             338450996                         POINT (-97.74223 30.26857)
             338450997                         POINT (-97.74297 30.26827)
             338451013                         POINT (-97.74118 30.27188)
             355352958                         POINT (-97.76334 30.24201)
...                                                                   ...
relation     5694381    POLYGON ((-97.69223 30.31612, -97.69216 30.316...
             5700520    POLYGON ((-97.84412 30.30748, -97.84418 30.307...
             5700911    POLYGON ((-97.74998 30.37397, -97.75001 30.373...
             5713869    POLYGON ((-97.83208 30.14015, -97.83210 30.140...
             10521767   POLYGON ((-97.74321 30.27663, -97.74321 30.276...

                               icon   color
element_type osmid
node         336605818         beer   green
             338450996         film     red
             338450997       coffee   green
             338451013       coffee   green
             355352958  institution  orange
...                             ...     ...
relation     5694381    institution  orange
             5700520    institution  orange
             5700911    institution  orange
             5713869    institution  orange
             10521767   institution  orange

[2492 rows x 5 columns]

In [20]:
# Assuming you have two DataFrames:
# 1. bus_stops_df: Contains 'stop_name', 'stop_lat', 'stop_lon'
# 2. pois_df: Contains 'name', 'geometry' (POI locations)

# Step 1: Add a geometry column to the bus stop DataFrame
unique_bus_stops['geometry'] = unique_bus_stops.apply(lambda row: Point(row['stop_lon'], row['stop_lat']), axis=1)

# Step 2: Convert both DataFrames to GeoDataFrames
# Set the CRS to WGS84 (EPSG:4326) for latitude/longitude
bus_stops_gdf = gpd.GeoDataFrame(unique_bus_stops, geometry='geometry', crs='EPSG:4326')
pois_gdf = gpd.GeoDataFrame(filtered_pois_df, geometry='geometry', crs='EPSG:4326')

# Step 3: Reproject both GeoDataFrames to a metric CRS (e.g., UTM) for accurate distance calculations
# Find the UTM zone for the centroid of the bus stops
utm_zone = pyproj.database.query_utm_crs_info(
    datum_name="WGS 84",
    area_of_interest=pyproj.aoi.AreaOfInterest(
        west_lon_degree=bus_stops_gdf.total_bounds[0],
        south_lat_degree=bus_stops_gdf.total_bounds[1],
        east_lon_degree=bus_stops_gdf.total_bounds[2],
        north_lat_degree=bus_stops_gdf.total_bounds[3],
    ),
)[0].code

pois_gdf['geometry'] = pois_gdf.geometry.centroid

bus_stops_gdf = bus_stops_gdf.to_crs(epsg=utm_zone)
pois_gdf = pois_gdf.to_crs(epsg=utm_zone)

# Step 4: Buffer the bus stops by 500 meters
bus_stops_gdf['buffered_geometry'] = bus_stops_gdf.geometry.buffer(1000)

# Step 5: Perform a spatial join to find POIs within 500 meters of bus stops
# Use `intersects` instead of `within` to handle mixed geometries
pois_within_500m = gpd.sjoin(pois_gdf, bus_stops_gdf, how='inner', predicate='within')
pois_within_500m

C:\Users\psle1\AppData\Local\Temp\ipykernel_12572\569873301.py:25: UserWarning: Geometry is in a geographic CRS. Results from 'centroid' are likely incorrect. Use 'GeoSeries.to_crs()' to re-project geometries to a projected CRS before this operation.

  pois_gdf['geometry'] = pois_gdf.geometry.centroid

Empty GeoDataFrame
Columns: [amenity, name, geometry, icon, color, index_right, trip_id, arrival_time, departure_time, stop_id, stop_sequence, pickup_type, drop_off_type, shape_dist_traveled, timepoint, direction_id, stop_name, stop_lat, stop_lon, buffered_geometry]
Index: []

## Data Loading to GCS

In [8]:
filtered_pois_df.to_csv('filtered_pois.csv', index=False)